services:
  nginx:
    image: nginx:1.27.5
    container_name: nginx
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - db_network

  mariadb:
    image: mariadb:11.8.1-ubi9-rc
    container_name: mariadb
    restart: always
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}

    volumes:
      - ./mariadb/db_backup:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - db_network

volumes:
  mariadb_data:

networks:
  db_network:
    driver: bridge

