services:
  nginx:
    image: nginx:1.27.5
    container_name: nginx
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  postgres:
    image: postgres:17.5
    restart: always
    volumes:
      - ./postgres/backup:/backup
      - ./postgres/data:/var/lib/postgresql/data

    env_file:
      - .env
    networks:
      - db_network


networks:
  db_network:
    driver: bridge

